export const ACTION_TYPES = {
  CALL_VENDOR: "CALL_VENDOR",
  WHATSAPP_VENDOR: "WHATSAPP_VENDOR",
  OPEN_MAPS: "OPEN_MAPS",
  BOOK_VENDOR: "BOOK_VENDOR",
  EMERGENCY_CONTACT: "EMERGENCY_CONTACT",
  NOTIFY_VENDOR: "NOTIFY_VENDOR"
};