export const TRUST_SIGNALS = {
  VERIFIED: 'VERIFIED',
  COMMUNITY_VERIFIED: 'COMMUNITY_VERIFIED',
  LOW_CONFIDENCE: 'LOW_CONFIDENCE',
  STALE: 'STALE',
  UNVERIFIED: 'UNVERIFIED',
  EMERGENCY_SAFE: 'EMERGENCY_SAFE',
  SUPPLY_GAP: 'SUPPLY_GAP',
  AMBIGUOUS: 'AMBIGUOUS'
} as const;

export type TrustSignal = keyof typeof TRUST_SIGNALS;
