// Cognition Response Finalizer
// BharatOS Phase 4 - Sovereign Response Boundary

import { Response } from 'express';
import { CognitionExecutionState, CognitionStage } from './runtime-state';
import { sendError, sendSuccess, ErrorCode } from '../../middleware/errorHandler';
import { advanceStage } from './runtime-orchestrator';

/**
 * FINALIZATION INVARIANT CHECK - Constitution Enforcement
 * Ensures exactly one response, telemetry exists, confidence exists
 */
function validateFinalizationInvariants(executionState: CognitionExecutionState) {
  if (!executionState.telemetry) {
    throw new Error("FINALIZATION_INVARIANT_VIOLATION: Telemetry missing");
  }
  if (!executionState.confidenceResult) {
    throw new Error("FINALIZATION_INVARIANT_VIOLATION: Confidence result missing");
  }
  if (!executionState.response) {
    throw new Error("FINALIZATION_INVARIANT_VIOLATION: Response missing");
  }
}

export function finalizeCognitionResponse(res: Response, executionState: CognitionExecutionState) {
  // ========================================
  // FINALIZATION INVARIANT CHECK
  // ========================================
  validateFinalizationInvariants(executionState);

  // Don't advance stage if already failed
  if (executionState.currentStage === CognitionStage.FAILED) {
    // Already failed, allow finalization to proceed without advancing
  } else {
    // Must be in RESPONSE_SYNTHESIS to finalize
    if (executionState.currentStage !== CognitionStage.RESPONSE_SYNTHESIS) {
      throw new Error(`Illegal finalization from ${executionState.currentStage}. Expected ${CognitionStage.RESPONSE_SYNTHESIS}`);
    }
    advanceStage(executionState, CognitionStage.RESPONSE_FINALIZATION);
  }

  const response = executionState.response;

  if (!response) {
    if (executionState.currentStage !== CognitionStage.FAILED) {
      advanceStage(executionState, CognitionStage.FAILED);
    }
    return sendError(res, 500, ErrorCode.INTERNAL_ERROR, "No response generated by cognition pipeline");
  }

  // Complete trace
  executionState.trace.completedAt = Date.now();
  executionState.trace.durationMs = executionState.trace.completedAt - executionState.trace.startedAt;
  executionState.trace.finalResponse = response;

  // Ensure telemetry truth is included
  if (executionState.telemetry) {
    response.telemetry = executionState.telemetry;
  }

  // Add execution metadata
  response.executionMetadata = {
    requestId: executionState.trace.requestId,
    totalStages: executionState.completedStages.length,
    failedStage: executionState.failedStage,
    durationMs: Date.now() - executionState.startedAt,
    deadlineMs: executionState.deadlineMs,
    finalStage: executionState.currentStage,
    stageTimings: Object.fromEntries(
      Object.entries(executionState.stageMetrics)
        .filter(([, metrics]) => metrics.durationMs)
        .map(([stage, metrics]) => [stage, metrics.durationMs])
    ),
    engineVersions: executionState.trace.engineVersions
  };

  // Add timestamp
  response.timestamp = new Date().toISOString();

  advanceStage(executionState, CognitionStage.COMPLETE);
  return sendSuccess(res, response);

}